name: mifever
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  google_sign_in: ^5.0.7
  pin_code_fields: ^8.0.1
  dotted_border: ^2.1.0
  sms_autofill: ^2.3.0
  calendar_date_picker2: ^0.5.3
  outline_gradient_button: ^2.0.1+1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  readmore: ^2.2.0
  grouped_list: ^5.1.2
  intl:
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  swipe_cards: ^2.0.0+1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.6
  fluttertoast: ^8.2.4
  flutter_sound: ^9.2.13
  # zego_uikit_prebuilt_call: ^3.17.2
  # zego_uikit_signaling_plugin: ^2.7.0
  firebase_messaging: ^14.7.17
  flutter_local_notifications: ^16.3.3
  dio: 
  geolocator: ^11.0.0
  flutter_google_places_hoc081098: ^2.0.0-beta.1
  location: ^5.0.3
  geocoding: ^2.2.0
  just_audio: ^0.9.36
  mailer: ^6.1.0
  file_picker: ^6.2.0
  path: ^1.8.3
  voice_message_package: ^2.1.0
  open_file: ^3.3.2
  skeletons: ^0.0.3
  flutter_stripe: ^10.1.1
  lottie: ^2.6.0
  video_thumbnail: ^0.5.3
  video_player: ^2.8.3
  share_plus: ^7.2.2
  emoji_picker_flutter: ^2.1.0
  translator_plus: ^1.0.1
  vibration: ^1.8.4
  photo_view: ^0.14.0
  flutter_super_html_viewer: ^0.1.0
  crop_your_image: ^1.0.2
  flutter_file_downloader: ^1.2.1
  timezone: ^0.9.2
  url_launcher_windows: ^3.1.1
  webview_flutter: ^2.0.13
  firebase_analytics: ^10.8.9
  mixpanel_flutter: ^2.2.0
  
  
  
   
   
   
    





dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/json/

 

  fonts: 
    - family: Manrope
      fonts: 
        - asset: assets/fonts/ManropeExtraBold.ttf
          weight: 800
        - asset: assets/fonts/ManropeRegular.ttf
          weight: 400
        - asset: assets/fonts/ManropeSemiBold.ttf
          weight: 600
        - asset: assets/fonts/ManropeBold.ttf
          weight: 700
        - asset: assets/fonts/ManropeMedium.ttf
          weight: 500
